// SPDX-License-Identifier: MIT
//
// Two BMI270s and a BMM150.
//
// The M135 puts a BMI270 at 0x69. The Tab5 already has one at 0x68. They sit
// on the same wire, so this file drives both and prints them side by side —
// that redundancy is most of the point of stacking the module.
//
// The BMM150 is not on this bus at all. It hangs off the BMI270's auxiliary
// I2C master, so it is reached by asking the 0x69 BMI270 to talk to it.

#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "tab5_bus.h"
#include "imu_example.h"

// Generated by tools/fetch_bmi270_config.sh from Bosch's BMI270-Sensor-API.
// See the README: without it the sensors answer their chip ID and nothing else.
#if __has_include("bmi270_config_file.h")
#include "bmi270_config_file.h"
#define HAVE_BMI270_CONFIG 1
#endif

static const char *TAG = "tab5_imu";

// --- BMI270 registers ---------------------------------------------------
#define BMI270_REG_CHIP_ID        0x00
#define BMI270_REG_ERR            0x02
#define BMI270_REG_STATUS         0x03
#define BMI270_REG_AUX_DATA       0x04
#define BMI270_REG_ACC_DATA       0x0C
#define BMI270_REG_GYR_DATA       0x12
#define BMI270_REG_INTERNAL_STAT  0x21
#define BMI270_REG_ACC_CONF       0x40
#define BMI270_REG_ACC_RANGE      0x41
#define BMI270_REG_GYR_CONF       0x42
#define BMI270_REG_GYR_RANGE      0x43
#define BMI270_REG_AUX_CONF       0x44
#define BMI270_REG_AUX_DEV_ID     0x4B
#define BMI270_REG_AUX_IF_CONF    0x4C
#define BMI270_REG_AUX_RD_ADDR    0x4D
#define BMI270_REG_AUX_WR_ADDR    0x4E
#define BMI270_REG_AUX_WR_DATA    0x4F
#define BMI270_REG_INIT_CTRL      0x59
#define BMI270_REG_INIT_ADDR_0    0x5B
#define BMI270_REG_INIT_ADDR_1    0x5C
#define BMI270_REG_INIT_DATA      0x5E
#define BMI270_REG_PWR_CONF       0x7C
#define BMI270_REG_PWR_CTRL       0x7D
#define BMI270_REG_CMD            0x7E

#define BMI270_CHIP_ID            0x24

// --- BMM150 registers (as seen through the aux interface) ---------------
#define BMM150_REG_CHIP_ID        0x40
#define BMM150_REG_DATA           0x42
#define BMM150_REG_POWER          0x4B
#define BMM150_REG_OPMODE         0x4C
#define BMM150_REG_REP_XY         0x51
#define BMM150_REG_REP_Z          0x52
#define BMM150_CHIP_ID            0x32

typedef struct {
    const char *label;
    uint8_t addr;
    i2c_master_dev_handle_t dev;
    bool configured;
    float acc_lsb_per_g;
    float gyr_lsb_per_dps;
} bmi270_t;

static bmi270_t s_module = { .label = "M135",  .addr = M135_BMI270_ADDR };
static bmi270_t s_onboard = { .label = "Tab5", .addr = 0x68 };
static bool s_mag_ok;

// --- init ---------------------------------------------------------------

#ifdef HAVE_BMI270_CONFIG
// The config blob goes out in chunks. Each chunk is addressed by a word
// offset split across INIT_ADDR_0 (low nibble) and INIT_ADDR_1, so the chunk
// size has to be even and the offset is bytes/2 — getting that shift wrong
// uploads a valid-looking image that fails INTERNAL_STATUS with no clue why.
#define INIT_CHUNK 64

static esp_err_t bmi270_upload_config(bmi270_t *s)
{
    uint8_t buf[1 + INIT_CHUNK];

    ESP_ERROR_CHECK(tab5_reg_write8(s->dev, BMI270_REG_PWR_CONF, 0x00));  // no adv power save
    vTaskDelay(pdMS_TO_TICKS(1));
    ESP_ERROR_CHECK(tab5_reg_write8(s->dev, BMI270_REG_INIT_CTRL, 0x00)); // begin upload

    for (size_t off = 0; off < sizeof(bmi270_config_file); off += INIT_CHUNK) {
        size_t n = sizeof(bmi270_config_file) - off;
        if (n > INIT_CHUNK) n = INIT_CHUNK;

        size_t words = off / 2;
        ESP_ERROR_CHECK(tab5_reg_write8(s->dev, BMI270_REG_INIT_ADDR_0, words & 0x0F));
        ESP_ERROR_CHECK(tab5_reg_write8(s->dev, BMI270_REG_INIT_ADDR_1, (words >> 4) & 0xFF));

        buf[0] = BMI270_REG_INIT_DATA;
        memcpy(buf + 1, bmi270_config_file + off, n);
        esp_err_t err = i2c_master_transmit(s->dev, buf, n + 1, pdMS_TO_TICKS(200));
        if (err != ESP_OK) return err;
    }

    ESP_ERROR_CHECK(tab5_reg_write8(s->dev, BMI270_REG_INIT_CTRL, 0x01)); // end upload

    // The datasheet allows up to 20 ms for the internal init to settle.
    for (int i = 0; i < 40; i++) {
        vTaskDelay(pdMS_TO_TICKS(5));
        uint8_t st = 0;
        if (tab5_reg_read(s->dev, BMI270_REG_INTERNAL_STAT, &st, 1) != ESP_OK) continue;
        if ((st & 0x0F) == 0x01) {
            ESP_LOGI(TAG, "%s: config uploaded, internal status ok", s->label);
            return ESP_OK;
        }
    }
    ESP_LOGE(TAG, "%s: config upload did not take (INTERNAL_STATUS never reached 0x01)", s->label);
    return ESP_ERR_INVALID_STATE;
}
#endif

static esp_err_t bmi270_open(bmi270_t *s)
{
    esp_err_t err = tab5_bus_add_device(s->addr, &s->dev);
    if (err != ESP_OK) return err;

    // A power-cycled BMI270 comes up in SPI mode and needs one dummy read to
    // latch onto I2C. The first read returning garbage is expected, not a fault.
    uint8_t id = 0;
    tab5_reg_read(s->dev, BMI270_REG_CHIP_ID, &id, 1);
    vTaskDelay(pdMS_TO_TICKS(2));

    err = tab5_reg_read(s->dev, BMI270_REG_CHIP_ID, &id, 1);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "%s: nothing at 0x%02X (%s)", s->label, s->addr, esp_err_to_name(err));
        return err;
    }
    if (id != BMI270_CHIP_ID) {
        ESP_LOGE(TAG, "%s: chip ID 0x%02X at 0x%02X, expected 0x24", s->label, id, s->addr);
        return ESP_ERR_NOT_FOUND;
    }
    ESP_LOGI(TAG, "%s: BMI270 at 0x%02X", s->label, s->addr);

#ifdef HAVE_BMI270_CONFIG
    err = bmi270_upload_config(s);
    if (err != ESP_OK) return err;

    ESP_ERROR_CHECK(tab5_reg_write8(s->dev, BMI270_REG_PWR_CTRL, 0x0E));  // acc + gyr + temp
    ESP_ERROR_CHECK(tab5_reg_write8(s->dev, BMI270_REG_ACC_CONF, 0xA8));  // 100 Hz, normal filter
    ESP_ERROR_CHECK(tab5_reg_write8(s->dev, BMI270_REG_ACC_RANGE, 0x01)); // +/- 4 g
    ESP_ERROR_CHECK(tab5_reg_write8(s->dev, BMI270_REG_GYR_CONF, 0xA9));  // 200 Hz, perf mode
    ESP_ERROR_CHECK(tab5_reg_write8(s->dev, BMI270_REG_GYR_RANGE, 0x00)); // +/- 2000 dps
    ESP_ERROR_CHECK(tab5_reg_write8(s->dev, BMI270_REG_PWR_CONF, 0x02));  // fifo self-wake

    s->acc_lsb_per_g = 32768.0f / 4.0f;
    s->gyr_lsb_per_dps = 32768.0f / 2000.0f;
    s->configured = true;
    vTaskDelay(pdMS_TO_TICKS(20));
#else
    ESP_LOGW(TAG, "%s: no config file, sensor stays in suspend (see README)", s->label);
#endif
    return ESP_OK;
}

// --- BMM150 through the BMI270's aux master -----------------------------

static esp_err_t aux_write(bmi270_t *s, uint8_t reg, uint8_t val)
{
    esp_err_t err = tab5_reg_write8(s->dev, BMI270_REG_AUX_WR_ADDR, reg);
    if (err != ESP_OK) return err;
    err = tab5_reg_write8(s->dev, BMI270_REG_AUX_WR_DATA, val);
    vTaskDelay(pdMS_TO_TICKS(5));
    return err;
}

static esp_err_t aux_read(bmi270_t *s, uint8_t reg, uint8_t *buf, size_t len)
{
    esp_err_t err = tab5_reg_write8(s->dev, BMI270_REG_AUX_RD_ADDR, reg);
    if (err != ESP_OK) return err;
    vTaskDelay(pdMS_TO_TICKS(5));
    return tab5_reg_read(s->dev, BMI270_REG_AUX_DATA, buf, len);
}

static esp_err_t bmm150_start(bmi270_t *s)
{
    // aux_en, on top of the acc/gyr bits already set.
    ESP_ERROR_CHECK(tab5_reg_write8(s->dev, BMI270_REG_PWR_CTRL, 0x0F));
    ESP_ERROR_CHECK(tab5_reg_write8(s->dev, BMI270_REG_AUX_DEV_ID, M135_BMM150_AUX_ADDR << 1));
    // Manual mode. Burst-read mode would have the BMI270 poll the magnetometer
    // on its own, but manual keeps the failure modes visible while bringing up.
    ESP_ERROR_CHECK(tab5_reg_write8(s->dev, BMI270_REG_AUX_IF_CONF, 0x80));
    ESP_ERROR_CHECK(tab5_reg_write8(s->dev, BMI270_REG_AUX_CONF, 0x08));  // ~100 Hz aux ODR
    vTaskDelay(pdMS_TO_TICKS(10));

    // Suspend -> sleep. The BMM150 answers nothing at all until this bit is
    // set, so a chip-ID read before it looks exactly like an absent part.
    ESP_ERROR_CHECK(aux_write(s, BMM150_REG_POWER, 0x01));
    vTaskDelay(pdMS_TO_TICKS(10));

    uint8_t id = 0;
    esp_err_t err = aux_read(s, BMM150_REG_CHIP_ID, &id, 1);
    if (err != ESP_OK || id != BMM150_CHIP_ID) {
        ESP_LOGW(TAG, "BMM150 not answering through aux (read 0x%02X, wanted 0x32)", id);
        return ESP_ERR_NOT_FOUND;
    }

    ESP_ERROR_CHECK(aux_write(s, BMM150_REG_REP_XY, 0x04));  // regular preset
    ESP_ERROR_CHECK(aux_write(s, BMM150_REG_REP_Z, 0x0E));
    ESP_ERROR_CHECK(aux_write(s, BMM150_REG_OPMODE, 0x00));  // normal mode
    vTaskDelay(pdMS_TO_TICKS(10));

    ESP_LOGI(TAG, "BMM150 at aux 0x%02X behind the M135 BMI270", M135_BMM150_AUX_ADDR);
    return ESP_OK;
}

// --- reporting ----------------------------------------------------------

static void read_and_log(bmi270_t *s)
{
    if (!s->configured) return;

    uint8_t raw[12];
    if (tab5_reg_read(s->dev, BMI270_REG_ACC_DATA, raw, sizeof(raw)) != ESP_OK) {
        ESP_LOGW(TAG, "%s: read failed", s->label);
        return;
    }
    int16_t ax = (int16_t)(raw[1]  << 8 | raw[0]);
    int16_t ay = (int16_t)(raw[3]  << 8 | raw[2]);
    int16_t az = (int16_t)(raw[5]  << 8 | raw[4]);
    int16_t gx = (int16_t)(raw[7]  << 8 | raw[6]);
    int16_t gy = (int16_t)(raw[9]  << 8 | raw[8]);
    int16_t gz = (int16_t)(raw[11] << 8 | raw[10]);

    ESP_LOGI(TAG, "  %-5s acc %+7.3f %+7.3f %+7.3f g   gyr %+8.2f %+8.2f %+8.2f dps",
             s->label,
             ax / s->acc_lsb_per_g, ay / s->acc_lsb_per_g, az / s->acc_lsb_per_g,
             gx / s->gyr_lsb_per_dps, gy / s->gyr_lsb_per_dps, gz / s->gyr_lsb_per_dps);
}

static void imu_task(void *arg)
{
    for (;;) {
        ESP_LOGI(TAG, "---");
        read_and_log(&s_onboard);
        read_and_log(&s_module);

        if (s_mag_ok) {
            uint8_t m[8];
            if (aux_read(&s_module, BMM150_REG_DATA, m, sizeof(m)) == ESP_OK) {
                // 13-bit X/Y, 15-bit Z, each left-aligned in its word. These are
                // raw counts: the BMM150's trim compensation lives in Bosch's
                // driver and is not reproduced here. Good enough for "is it
                // moving", not for a calibrated heading.
                int16_t mx = (int16_t)((m[1] << 8 | (m[0] & 0xF8))) / 8;
                int16_t my = (int16_t)((m[3] << 8 | (m[2] & 0xF8))) / 8;
                int16_t mz = (int16_t)((m[5] << 8 | (m[4] & 0xFE))) / 2;
                ESP_LOGI(TAG, "  mag   %+6d %+6d %+6d (raw counts, uncompensated)", mx, my, mz);
            }
        }
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}

esp_err_t imu_example_start(void)
{
#ifndef HAVE_BMI270_CONFIG
    ESP_LOGW(TAG, "built without bmi270_config_file.h");
    ESP_LOGW(TAG, "run ./tools/fetch_bmi270_config.sh, then rebuild");
#endif

    // The Tab5's own IMU is optional here; a failure there should not stop the
    // module from coming up.
    if (bmi270_open(&s_onboard) != ESP_OK) {
        ESP_LOGW(TAG, "Tab5 onboard BMI270 unavailable, continuing with the module only");
    }

    esp_err_t err = bmi270_open(&s_module);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "M135 BMI270 not found. Is the module seated and EXT5V on?");
        return err;
    }

    if (s_module.configured) {
        s_mag_ok = (bmm150_start(&s_module) == ESP_OK);
    }

    xTaskCreate(imu_task, "imu", 4096, NULL, 4, NULL);
    return ESP_OK;
}
