#!/usr/bin/env bash
# Extracts the BMI270 configuration blob from Bosch's reference driver into
# main/bmi270_config_file.h.
#
# The BMI270 ships with no usable firmware in ROM. Until this ~8 KB image is
# uploaded over I2C the part answers its chip ID and does nothing else — no
# accelerometer, no gyroscope, no aux interface, and no error either. The blob
# is not redistributable-by-vibes but it is BSD-3-Clause, so vendoring it is
# fine; it is just too large and too opaque to paste into a source file by hand.
#
#   ./tools/fetch_bmi270_config.sh            fetch and generate
#   ./tools/fetch_bmi270_config.sh --revert   delete the generated header

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$HERE/main/bmi270_config_file.h"
SRC_URL="https://raw.githubusercontent.com/boschsensortec/BMI270-Sensor-API/master/bmi270.c"

if [ "${1:-}" = "--revert" ]; then
    rm -f "$OUT"
    echo "removed $OUT"
    echo "delete build/ and rebuild to go back to chip-ID-only mode"
    exit 0
fi

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

echo "fetching $SRC_URL"
curl -fsSL "$SRC_URL" -o "$TMP"

# The array is declared as
#   const uint8_t bmi270_config_file[] = { 0x..., ... };
# spanning a few thousand lines. Pull from the declaration to the first
# closing brace and keep only the hex bytes, so the exact formatting Bosch
# happens to use this month does not matter.
python3 - "$TMP" "$OUT" <<'PY'
import re, sys

src, out = sys.argv[1], sys.argv[2]
text = open(src, encoding="utf-8", errors="replace").read()

m = re.search(r"bmi270_config_file\s*\[\s*\]\s*=\s*\{(.*?)\}\s*;", text, re.S)
if not m:
    sys.exit("could not find bmi270_config_file[] — did upstream rename it?")

body = re.sub(r"/\*.*?\*/", "", m.group(1), flags=re.S)
body = re.sub(r"//[^\n]*", "", body)
bytes_ = re.findall(r"0[xX][0-9a-fA-F]{1,2}", body)

if len(bytes_) < 4096:
    sys.exit(f"only {len(bytes_)} bytes extracted; that is too small to be the real image")
if len(bytes_) % 2:
    sys.exit(f"{len(bytes_)} bytes is odd; the upload is word-addressed and must be even")

with open(out, "w") as f:
    f.write("// Generated by tools/fetch_bmi270_config.sh. Do not edit.\n")
    f.write("// Source: boschsensortec/BMI270-Sensor-API, BSD-3-Clause.\n")
    f.write("#pragma once\n#include <stdint.h>\n\n")
    f.write("static const uint8_t bmi270_config_file[] = {\n")
    for i in range(0, len(bytes_), 12):
        f.write("    " + ", ".join(b.lower() for b in bytes_[i:i + 12]) + ",\n")
    f.write("};\n")

print(f"wrote {out} ({len(bytes_)} bytes)")
PY

# A stale build directory will happily reuse the old object files and the
# sensors stay dead with a header sitting right there, which is a confusing
# half hour.
rm -rf "$HERE/build"
echo "removed build/; run idf.py build"
