#!/usr/bin/env bash
# Fetches Bosch's BMI270 and BMM150 reference drivers into
# components/bosch_sensortec/, where the IDF component manager picks them up.
#
# Why vendor these rather than drive the registers directly: the BMI270's
# auxiliary I2C master is not a bus you can drive by writing the obvious
# registers in the obvious order. Its write primitive needs AUX_WR_DATA set
# *before* AUX_WR_ADDR, because writing the address is what triggers the
# transaction; it has to poll the aux_busy bit between operations; and it has
# to drop advanced power save around each transfer. Several attempts at a
# hand-rolled version failed with aux_err on every transaction, and none of
# the failures pointed at the cause. M5's own driver wraps this same API.
#
#   ./tools/fetch_bosch_drivers.sh            fetch
#   ./tools/fetch_bosch_drivers.sh --revert   remove
#
# Both drivers are BSD-3-Clause. They are gitignored rather than committed,
# for the same reason as the config blob: byte-exact fetches from a pinned
# upstream, under a different licence to this repo.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="$HERE/components/bosch_sensortec"

BMI270_URL="https://raw.githubusercontent.com/boschsensortec/BMI270-Sensor-API/master"
BMM150_URL="https://raw.githubusercontent.com/boschsensortec/BMM150-Sensor-API/master"

BMI270_FILES="bmi2.c bmi2.h bmi2_defs.h bmi270.c bmi270.h"
BMM150_FILES="bmm150.c bmm150.h bmm150_defs.h"

if [ "${1:-}" = "--revert" ]; then
    rm -rf "$DEST" "$HERE/build"
    echo "removed $DEST and build/"
    exit 0
fi

mkdir -p "$DEST"

for f in $BMI270_FILES; do
    echo "fetching $f"
    curl -fsSL "$BMI270_URL/$f" -o "$DEST/$f"
done
for f in $BMM150_FILES; do
    echo "fetching $f"
    curl -fsSL "$BMM150_URL/$f" -o "$DEST/$f"
done

# Sanity check: bmi270.c carries the 8 KB config image, so a truncated or
# redirected download shows up here rather than as a sensor that silently
# fails to initialise.
if ! grep -q "bmi270_config_file" "$DEST/bmi270.c"; then
    echo "bmi270.c does not contain bmi270_config_file[] — bad download?" >&2
    exit 1
fi

cat > "$DEST/CMakeLists.txt" <<'EOF'
# Generated by tools/fetch_bosch_drivers.sh.
idf_component_register(
    SRCS "bmi2.c" "bmi270.c" "bmm150.c"
    INCLUDE_DIRS "."
)
# Bosch's drivers are not warning-clean under IDF's default flags, and the
# warnings are all in vendored code nobody here should be editing.
target_compile_options(${COMPONENT_LIB} PRIVATE -Wno-unused-but-set-variable -Wno-sign-compare)
EOF

# A stale build directory reuses old objects and leaves the sensor dead with
# perfectly good sources sitting right there.
rm -rf "$HERE/build"
echo
echo "vendored into components/bosch_sensortec; run idf.py build"
echo "note: tools/fetch_bmi270_config.sh is now redundant — the config image"
echo "      ships inside bmi270.c, and imu_example.c no longer includes the"
echo "      generated header."
